# datasource

spring:
  datasource:
    url: jdbc:mysql:///springboot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper location
  type-aliases-package: com.example.springbootmybatis.domain

  # config-locatoin: # mybatis config file